name: Coverage

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Compile contracts
        run: npm run compile

      - name: Run coverage
        run: npm run test:coverage

      - name: Generate Coverage Report
        run: |
          echo "## Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ -f coverage/lcov-report/index.html ]; then
            echo "✅ Coverage report generated successfully" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Summary" >> $GITHUB_STEP_SUMMARY
            if [ -f coverage/coverage-summary.json ]; then
              node -e "
                const fs = require('fs');
                const coverage = JSON.parse(fs.readFileSync('coverage/coverage-summary.json', 'utf8'));
                const total = coverage.total;
                console.log('| Metric | Coverage |');
                console.log('|--------|----------|');
                console.log('| Lines | ' + total.lines.pct + '% |');
                console.log('| Functions | ' + total.functions.pct + '% |');
                console.log('| Branches | ' + total.branches.pct + '% |');
                console.log('| Statements | ' + total.statements.pct + '% |');
              " >> $GITHUB_STEP_SUMMARY
            fi
          else
            echo "❌ Coverage report not found" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 30

      - name: Update Coverage Documentation
        run: |
          mkdir -p docs
          echo "# Coverage Report" > docs/coverage.md
          echo "Generated on: $(date)" >> docs/coverage.md
          echo "" >> docs/coverage.md
          if [ -f coverage/coverage-summary.json ]; then
            echo "## Summary" >> docs/coverage.md
            node -e "
              const fs = require('fs');
              const coverage = JSON.parse(fs.readFileSync('coverage/coverage-summary.json', 'utf8'));
              const total = coverage.total;
              console.log('| Metric | Coverage |');
              console.log('|--------|----------|');
              console.log('| Lines | ' + total.lines.pct + '% |');
              console.log('| Functions | ' + total.functions.pct + '% |');
              console.log('| Branches | ' + total.branches.pct + '% |');
              console.log('| Statements | ' + total.statements.pct + '% |');
            " >> docs/coverage.md
          fi

      - name: Commit Coverage Report
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/coverage.md
          git diff --staged --quiet || git commit -m "Update coverage report [skip ci]"
          git push
